# Generated by Django 2.0.5 on 2018-07-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Masjid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, default='', max_length=1000)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('fajr', models.TimeField()),
                ('zohar', models.TimeField()),
                ('asr', models.TimeField()),
                ('maghrib', models.TimeField()),
                ('isha', models.TimeField()),
                ('jumma', models.TimeField()),
                ('last_modified', models.DateField(auto_now=True)),
                ('contact', models.ManyToManyField(blank=True, null=True, to='masajid_finder.Contact')),
            ],
        ),
    ]
